### ISSUE TITLE
Identify DGGS through literal type or URI?

### ISSUE THREAD

**Issue by situx** [opengeospatial/ogc-geosparql#339] opened 2022-05-25 15:35 UTC
The current GeoSPARQL 1.1 specification draft defines one type geo:dggsLiteral and allows for the definition of other DGGS types like auspix.
Currently, these types are actual literal types, so a filter statement in a SPARQL query that intends to filter out all DGGS literals in a graph needs to know all these different literal types to perform filtering.

For WKT, we had a different solution. We included a URI statement at the beginning of the literal value.
In the future, we intend to also include a geo:inSRS property linking a geometry to its Spatial Reference System.

Why did we choose to define literal types for DGGS and did not follow the pattern of defining a URI in front of a DGGS literal?

I think it might be a better way to have a single literal type and not give users the potential to define new literal types that are hard to filter in SPARQL queries.

What do you think? Or am I missing something obvious here?

**Comment by FransKnibbe** [comment] 2022-05-25 16:47
> Why did we choose to define literal types for DGGS and did not follow the pattern of defining a URI in front of a DGGS literal?

Because it is a bad pattern? See also [issue 31](https://github.com/opengeospatial/ogc-geosparql/issues/31).

**Comment by FransKnibbe** [comment] 2022-05-25 17:01
If a pattern that we know should be reverted is introduced now, the SWG will incur extra future work. I'd say it is better to do it right from the start.

To specify the DGGS of a DGGS geometry, a property like geo:hasDGGS seems appropriate, if a DGGS geometry literal can not be counted on to disclose the DGGS itself.

**Comment by jabhay** [comment] 2022-06-15 20:26
Duplicate of #351

**Closed by jabhay** 2022-06-15 20:26 UTC
