### ISSUE TITLE
Extend expressive power of ontology for encountered use cases

### ISSUE THREAD

**Issue by lvdbrink** [opengeospatial/ogc-geosparql#9] opened 2019-10-18 13:49 UTC
**Official change request**: [OGC CR 601](http://ogc.standardstracker.org/show_request.cgi?id=601)

GeoSPARQL Extensions Ontology

We request extensions to the GeoSPARQL OWL ontology that includes details it doesn't cater for such as indicating spatial resolution, areas, proportional relations (e.g. area overlaps) and roles for multiple Geometry objects relating to a single Feature.
 
We have packaged the extensions we are already using in an ontology that is mostly built on GeoSPARQL but it also uses elements from QUDT and the some supporting datatype vocabularies. That "[GeoSPARQL Extensions Ontology](https://github.com/CSIRO-enviro-informatics/geosparql-ext-ont/)" is online and we have also [attached a copy](https://github.com/opengeospatial/geosemantics-dwg/blob/master/CR601attachment.txt).

**Comment by jabhay** [comment] 2020-09-23 11:24
MoSCoW poll created

[![](https://api.gh-polls.com/poll/01EJXBAME5DXQFRYEQRSX50CCX/Must)](https://api.gh-polls.com/poll/01EJXBAME5DXQFRYEQRSX50CCX/Must/vote)
[![](https://api.gh-polls.com/poll/01EJXBAME5DXQFRYEQRSX50CCX/Should)](https://api.gh-polls.com/poll/01EJXBAME5DXQFRYEQRSX50CCX/Should/vote)
[![](https://api.gh-polls.com/poll/01EJXBAME5DXQFRYEQRSX50CCX/Could)](https://api.gh-polls.com/poll/01EJXBAME5DXQFRYEQRSX50CCX/Could/vote)
[![](https://api.gh-polls.com/poll/01EJXBAME5DXQFRYEQRSX50CCX/Won%27t)](https://api.gh-polls.com/poll/01EJXBAME5DXQFRYEQRSX50CCX/Won%27t/vote)

**Comment by jabhay** [comment] 2020-10-02 14:41
Duplicate of #33

**Closed** 2020-10-02 14:41 UTC
