### ISSUE TITLE
geof:aggConcatLines is undefined

### ISSUE THREAD

**Issue by nicholascar** [opengeospatial/ogc-geosparql#343] opened 2022-06-01 12:57 UTC
`geof:aggConcatLines` appears in our Major Changes table and the Annex B but it's undefined in the main text and the functions RDF.

I have put a placeholder in: @situx please complete this function definition in the ADOC & RDF.

**Comment by situx** [comment] 2022-06-01 12:59
Hi @nicholascar it was removed as part of my large pull request because it seemed to be a duplicate of aggUnion.
What I would do is remove the definitions in Annex B instead.

**Comment by nicholascar** [comment] 2022-06-01 16:19
OK, I'll do that now

**Closed** 2022-06-01 20:15 UTC
Labels: bug
